name: PostgreSQL for GitHub Actions

on: 
  workflow_dispatch

jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@master
            
   # Authentication
    - uses: azure/login@v1.6.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}

      # Step 3: Run PostgreSQL script
    - uses: azure/postgresql@v1
      with:
          server-name: test897
          connection-string: ${{ secrets.AZURE_POSTGRESQL_CONNECTION_STRING }}
          plsql-file: './data.sql'

      # Step 4: Azure logout
    - name: logout
      run: |
          az logout
